### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by RaccoonHours** [kurozenzen/r34-react#3]
**Describe the feature**
I'm sorry for so many suggestions ahaha, but I was wondering if it would be easy to add 1. A horizontal scrolling system, similar to something like Google images where if you click or press on a picture, it would enlarge it, then you scroll sidewaysfor the next image? And 2. Maybe          something like a page system? Only as every time I use the site, I scroll last the same dozen images to get back to my 'place', so maybe adding a page system, I'm which you could go directly to a page would be a solution? Once again I'm truly sorry for making so many suggestions, and I hope I'm not coming across as needy or entitled, I'm just a huge fan of your app! And am excited to see it grow♡

**Comment by kurozenzen** [comment]
Haha, dont worry about it.

1. The horizontal scrolling bit is actually in the works. I wanna make it so you can fullscreen a post and the swipe to get to the next one (same as Google images as you mentioned).
2. The page system is already there under the hood. I just have to expose it in a nice way. Maybe I will make an alternative layout focused on pages instead of infinite loading. 

All your suggestions are greatly appreciated though. I was running out of ideas so those are some welcome challenges.

**Comment by kurozenzen** [comment]
Part 2 is done. Check the settings and switch the layout to "pages". Again, a bit experimental... But I can improve it later.

**Comment by RaccoonHours** [comment]
THANK YOU SO MUCH! I'm honestly so blown away how quickly and effectively you added all of my suggestions, I'm super super thankful!! Thanks so much!

**Comment by kurozenzen** [comment]
Oh you are gonna like this then...

I have added a basic horizontal scrolling thing as well. I don't know if its quite what you want but I still wanna improve it a lot anyways. Let me know if you have any suggestions 💪

**Comment by RaccoonHours** [comment]
Holy shit ahahah thanks so much! Also I may just be super dumb but I can't figure out how you've implemented the scrolling, is it something I have to activate in settings?

**Comment by kurozenzen** [comment]
ah yeah. sorry.  click the fullscreen icon on a post.

**Comment by RaccoonHours** [comment]
Oh true, just figured it out, thanks so much for taking my suggestions on board!!!
