### ISSUE TITLE
Can't search more than one artist tag at a time

### ISSUE THREAD

**Issue by Yimellovzski** [kurozenzen/r34-react#59]
**Describe the bug**
when inputting more than one tag and hit search, it does not show any results whatsoever.

**Screenshots**
![tag_fail](https://user-images.githubusercontent.com/45341995/180628099-c56a2bd0-d747-4fb4-be06-63cff7aec021.png)
**Device**
Linux Pop!_OS 22.04 using qutebrowser with javascript enabled.
**Additional information**

**Comment by kurozenzen** [comment]
I will have a look.

But i see that both of your tags are quite small. 31 and 148 posts respectively. Are you sure that combination has posts in it?

You could check by searching the same on rule34.xxx.

**Comment by Yimellovzski** [comment]
Yeah, they have posts in them, since both of them are artist tags.

**Comment by kurozenzen** [comment]
Ah i think i know what the problem is.

By default a search for `tag A` and `tag B` will only show post that have `tag A` *and* `tag B` on them.

Based on those tags being artist tags, I think you want to show posts that have `tag A` *or* `tag B`, right? Cause very few posts are made by two artists.

 To do that you have to use optional tags. It's very easy, just click the little plus in front of the searchbar until it is a `~`. 

Tags added this way will be optional but every post in the result will have at least one off all optional tags on it.

**Comment by Yimellovzski** [comment]
Oh thanks for the tip! Images are showing normally now. I just had to set both (artist) tags as `~` tags for them to show. I should have figured that out sooner lol

![working_tags](https://user-images.githubusercontent.com/45341995/180895294-dcdc888b-7f82-4bce-94fb-6a950b750032.png)
